spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console   # Default URL


# Replace this your db driver

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/todosdb   # PostgreSQL URL
#    username: postgres                               # DB username
#    password: Pass1234                         # DB password
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update       # Automatically create/update tables (use 'validate' or 'none' in production)
#    show-sql: true           # Print SQL in console
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
